#!/bin/sh
mkdir -p src/{main,test}/{java,resources,scala}
mkdir lib project target

# create an initial build.sbt file
echo Name of project?
read NAME

echo Creating build.sbt
echo 'name := "$NAME"
version := "1.0"
scalaVersion := "2.11.0"
libraryDependencies ++= Seq(
  "org.specs2" %% "specs2" % "2.2.2" % "test"
  )' > build.sbt

echo Creating gitignore
echo '*.class
*.log

# sbt specific
.cache
.history
.lib/
dist/*
target/
lib_managed/
src_managed/
project/boot/
project/plugins/project/

# Scala-IDE specific
.scala_dependencies
.worksheet' > .gitignore
